server:
  port: 8080

spring:

  application:
    name: insurance-quote

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:InsuranceQuoteDB
    username: admin
    password: admin
    driverClassName: org.h2.Driver

  jpa:
    deferDatasourceInitialization: true

  artemis:
    mode: embedded
    embedded:
      persistent: false
      securityEnabled: false
      queues:
        - insurance-quote-received
        - insurance-policy-created

  springdoc:
    swaggerUi:
      path: /swagger-ui
    apiDocs:
      path: /v3/api-docs